-- Kullanýcý tanýmý tablosu
CREATE TABLE user_definition (
    user_id NUMBER PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(64) NOT NULL, 
    login_attempts NUMBER DEFAULT 0,
    last_login_date DATE,
    is_locked NUMBER DEFAULT 0
);


drop table user_details
drop table user_definition
drop table user_address

CREATE TABLE user_details (
    user_details_id NUMBER PRIMARY KEY,
    name_ varchar2(50),
    surname varchar2(50),
    gender VARCHAR2(50), 
    address_id number,
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20),
    FOREIGN KEY (user_details_id) REFERENCES user_definition(user_id),
    foreign key (address_id) references user_address(address_id)
);


CREATE TABLE user_address (
    address_id NUMBER PRIMARY KEY,
    user_id NUMBER,
    street VARCHAR2(255),
    city VARCHAR2(50),
    state VARCHAR2(50),
    postal_code VARCHAR2(20),
    country_id number,
    FOREIGN KEY (user_id) REFERENCES user_definition(user_id),
    foreign key (country_id) references countries(country_id)
);

CREATE TABLE regions(
       region_id number primary key,
       region_name varchar2(50)
);

CREATE TABLE countries(
       country_id number primary key,
       country_name varchar2(50),
       region_id number,
       foreign key (region_id) references regions(region_id)
);       
       

CREATE TABLE Product_Category (
    category_id NUMBER PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL,
    parent_category_id NUMBER,
    CONSTRAINT fk_parent_category FOREIGN KEY (parent_category_id) REFERENCES Product_Category(category_id)
);

CREATE TABLE Product (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER NOT NULL,
    category_id NUMBER,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES Product_Category(category_id)
);

CREATE TABLE Basket (
    basket_id NUMBER,
    user_id NUMBER,
    product_id NUMBER,
    quantity NUMBER default 0,
    price NUMBER default 0,
    CONSTRAINT fk_basket_user FOREIGN KEY (user_id) REFERENCES user_definition(user_id),
    CONSTRAINT fk_basket_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    PRIMARY KEY(basket_id,user_id,product_id)
);

CREATE TABLE Purchase (
    purchase_id NUMBER PRIMARY KEY,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id NUMBER,
    total_price NUMBER DEFAULT 0,
    CONSTRAINT fk_user_purchase FOREIGN KEY (user_id) REFERENCES user_definition(user_id)
);

CREATE TABLE Purchase_Item (
    purchase_item_id NUMBER PRIMARY KEY,
    purchase_id NUMBER,
    product_id NUMBER,
    quantity NUMBER DEFAULT 0,
    price NUMBER DEFAULT 0,
    CONSTRAINT fk_purchase_item_purchase FOREIGN KEY (purchase_id) REFERENCES Purchase(purchase_id),
    CONSTRAINT fk_purchase_item_product FOREIGN KEY (product_id) REFERENCES Product(product_id)
);

CREATE TABLE Favorite (
    favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY, --Her favaourite_id deðerinin unique olmasý için. Kolay yoldan kast ettiðim bu.
    user_id NUMBER,
    product_id NUMBER,
    CONSTRAINT pk_favorite PRIMARY KEY (favorite_id),
    CONSTRAINT fk_user_favorite FOREIGN KEY (user_id) REFERENCES user_definition(user_id),
    CONSTRAINT fk_product_favorite FOREIGN KEY (product_id) REFERENCES Product(product_id)
);
  
       
drop table Purchase;
drop table Purchase_Item;
SELECT * FROM all_directories;
CREATE OR REPLACE DIRECTORY EXPORT_DIR AS '/home/oracle';
